-- ============================================================================
-- ARTICLES SEED INDEX FILE
-- ============================================================================
-- This file orchestrates the loading of article seed data from split files.
--
-- Split Structure:
--   1. articles_manual_seed.sql     - 12 manual/guide articles
--   2. articles_news_seed.sql       - 6 news articles
--   3. articles_faq_troubleshoot_seed.sql - 6 FAQ + 8 troubleshooting articles
--
-- Total: 32 articles
--
-- Template Variables:
--   All content uses {{variable.path}} syntax resolved at runtime.
--   See: decodables-fe/components/static-pages/types.ts for TemplateContext
--
-- Usage:
--   Run each seed file separately, or use \i to include them:
--   \i articles_manual_seed.sql
--   \i articles_news_seed.sql
--   \i articles_faq_troubleshoot_seed.sql
--
-- ============================================================================

-- ============================================================================
-- PRE-SEED CLEANUP (Optional)
-- ============================================================================
-- Uncomment to clear existing articles before re-seeding
-- DELETE FROM articles WHERE category IN ('manual', 'news', 'faq', 'troubleshooting');

-- ============================================================================
-- LOAD SEED FILES
-- ============================================================================
-- Note: In PostgreSQL, use \i for includes. In application code, execute
-- each file separately in order.

-- Option 1: PostgreSQL psql client
-- \i articles_manual_seed.sql
-- \i articles_news_seed.sql
-- \i articles_faq_troubleshoot_seed.sql

-- Option 2: Manual execution (copy-paste each file's content)
-- See individual files for content

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Count articles by category (run after seeding)
-- SELECT category, COUNT(*) as count
-- FROM articles
-- WHERE is_published = true
-- GROUP BY category
-- ORDER BY category;

-- Expected results:
-- | category        | count |
-- |-----------------|-------|
-- | faq             | 6     |
-- | manual          | 12    |
-- | news            | 6     |
-- | troubleshooting | 8     |
-- Total: 32 articles

-- List all articles with basic info
-- SELECT slug, title, category, is_featured, sort_order
-- FROM articles
-- WHERE is_published = true
-- ORDER BY category, sort_order;

-- ============================================================================
-- ARTICLE CATEGORIES REFERENCE
-- ============================================================================
--
-- MANUAL (12 articles):
--   - getting-started                   Getting Started with Make Decodables
--   - ai-image-generation               AI Image Generation Guide
--   - designing-pages                   Designing Your Pages
--   - exporting-and-printing            Exporting and Printing Your Books
--   - folding-instructions              How to Fold Your Mini-Book
--   - ocr-smart-scan                    OCR Smart Scan Guide
--   - marketplace-guide                 Marketplace Guide
--   - using-stickers                    Using Stickers and Assets
--   - classroom-tips                    Classroom Tips for Teachers
--   - subscription-and-credits          Subscription and Credits Guide
--   - troubleshooting-guide             Troubleshooting Guide
--   - faq                               Frequently Asked Questions
--
-- NEWS (6 articles):
--   - welcome-to-make-decodables        Platform Launch
--   - ai-image-generation-now-available AI Feature Announcement
--   - marketplace-now-open              Marketplace Launch
--   - teacher-spotlight-sarah-johnson   User Story
--   - new-spring-templates-collection   Template Collection
--   - january-2026-platform-update      Platform Update
--
-- FAQ (6 articles):
--   - faq-getting-started               Getting Started FAQ
--   - faq-credits-pricing               Credits & Pricing FAQ
--   - faq-features-plans                Features & Plans FAQ
--   - faq-export-printing               Export & Printing FAQ
--   - faq-marketplace                   Marketplace FAQ
--   - faq-account-support               Account & Support FAQ
--
-- TROUBLESHOOTING (8 articles):
--   - troubleshooting-insufficient-credits    Credit errors
--   - troubleshooting-trial-expired           Trial expiration
--   - troubleshooting-project-limit           Project limits
--   - troubleshooting-content-policy          Content violations
--   - troubleshooting-save-failed             Save failures
--   - troubleshooting-upload-failed           Upload issues
--   - troubleshooting-checkout-failed         Payment errors
--   - troubleshooting-zip-requires-pro        Feature restrictions
--
-- ============================================================================
-- END OF INDEX FILE
-- ============================================================================
