"""
自动生成 field_mappings.py 映射表

从数据库 Schema (v3 migrations) 自动提取所有表的字段，生成映射骨架。

Usage:
    python scripts/tools/generate_field_mappings.py

Output:
    打印所有 60 张表的映射定义（需人工审查后添加到 field_mappings.py）
"""

import re
from pathlib import Path
from typing import Dict, List, Tuple

# 特殊映射规则
SPECIAL_MAPPINGS = {
    'id': {
        'profiles': 'user_id',
        'projects': 'project_id',
        'assets': 'asset_id',
        'marketplace_listings': 'listing_id',
        'marketplace_purchases': 'purchase_id',
        'credit_transactions': 'transaction_id',
        'system_configs': 'config_key',  # system_configs 使用 key 作为主键
        'experiments': 'experiment_id',
        'feature_flags': 'flag_id',
        'notifications': 'notification_id',
        'campaigns': 'campaign_id',
        'support_tickets': 'ticket_id',
    },
    'user_id': {
        'marketplace_purchases': 'buyer_id',  # 购买表中 user_id → buyer_id
        'marketplace_listings': 'seller_id',  # 注意: listings 使用 seller_id
    }
}

def extract_create_table(sql_content: str) -> List[Tuple[str, str]]:
    """提取所有 CREATE TABLE 语句"""
    pattern = r'CREATE TABLE (\w+) \((.*?)\);'
    matches = re.findall(pattern, sql_content, re.DOTALL | re.MULTILINE)
    return matches

def parse_columns(table_definition: str) -> List[Tuple[str, str]]:
    """解析表定义，提取所有列名和类型"""
    columns = []
    lines = table_definition.split('\n')

    for line in lines:
        line = line.strip()

        # 跳过注释、约束、空行
        if not line or line.startswith('--') or line.startswith('CONSTRAINT') or line.startswith('CHECK'):
            continue

        # 匹配列定义: column_name TYPE ...
        match = re.match(r'(\w+)\s+([\w\(\),\[\]]+)', line)
        if match:
            col_name = match.group(1)
            col_type = match.group(2)
            columns.append((col_name, col_type))

    return columns

def generate_mapping(table_name: str, columns: List[Tuple[str, str]]) -> str:
    """生成映射字典定义"""
    mapping_name = f"{table_name.upper()}_DB_TO_DOMAIN"

    lines = [
        f"# ============================================================",
        f"# {table_name} 表",
        f"# ============================================================",
        f"{mapping_name}: Dict[str, str] = {{",
    ]

    for col_name, col_type in columns:
        # 应用特殊映射规则
        domain_field = col_name

        if col_name == 'id' and table_name in SPECIAL_MAPPINGS['id']:
            domain_field = SPECIAL_MAPPINGS['id'][table_name]
        elif col_name == 'user_id' and table_name in SPECIAL_MAPPINGS['user_id']:
            domain_field = SPECIAL_MAPPINGS['user_id'][table_name]
        elif col_name == 'key' and table_name == 'system_configs':
            domain_field = 'config_key'

        # 添加类型注释
        type_comment = get_type_comment(col_type)
        lines.append(f"    '{col_name}': '{domain_field}',  # {type_comment}")

    lines.append("}")
    lines.append("")

    return '\n'.join(lines)

def get_type_comment(col_type: str) -> str:
    """获取类型注释"""
    if 'TEXT' in col_type or 'VARCHAR' in col_type:
        return col_type.split()[0]
    elif 'INTEGER' in col_type or 'INT' in col_type:
        return 'INTEGER'
    elif 'BOOLEAN' in col_type:
        return 'BOOLEAN'
    elif 'TIMESTAMPTZ' in col_type:
        return 'TIMESTAMPTZ'
    elif 'UUID' in col_type:
        return 'UUID'
    elif 'NUMERIC' in col_type:
        return col_type
    elif 'JSONB' in col_type:
        return 'JSONB'
    elif col_type.startswith('TEXT[]'):
        return 'TEXT[]'
    else:
        return col_type

def main():
    # 读取 v3 migration 文件
    migrations_dir = Path(__file__).parent.parent.parent / 'migrations' / 'v3'

    all_tables = {}

    for sql_file in sorted(migrations_dir.glob('*.sql')):
        print(f"# Reading {sql_file.name}...", file=__import__('sys').stderr)
        content = sql_file.read_text()

        tables = extract_create_table(content)
        for table_name, table_def in tables:
            columns = parse_columns(table_def)
            if columns:
                all_tables[table_name] = columns

    print(f"# Found {len(all_tables)} tables", file=__import__('sys').stderr)
    print()

    # 生成映射
    print('"""')
    print('Auto-generated field mappings (PART 2 - 补充映射)')
    print('Generated by: scripts/tools/generate_field_mappings.py')
    print('Date: 2026-01-10')
    print()
    print('⚠️  请人工审查以下映射，特别注意:')
    print('1. user_id vs buyer_id/seller_id/owner_id 等特殊字段')
    print('2. id → {table_name}_id 的转换是否正确')
    print('3. 是否有嵌套路径 (如 balance.monthly)')
    print('"""')
    print()
    print('from typing import Dict')
    print()

    # 按字母顺序生成
    for table_name in sorted(all_tables.keys()):
        # 跳过已有映射的表
        if table_name in ['profiles', 'credit_transactions', 'projects',
                          'marketplace_listings', 'marketplace_purchases', 'system_configs']:
            continue

        columns = all_tables[table_name]
        mapping = generate_mapping(table_name, columns)
        print(mapping)

    print()
    print('# ============================================================')
    print('# 映射统计')
    print('# ============================================================')
    print(f'# 总表数: {len(all_tables)}')
    print(f'# 已有映射: 6 (profiles, credit_transactions, projects, marketplace_listings, marketplace_purchases, system_configs)')
    print(f'# 新增映射: {len(all_tables) - 6}')

if __name__ == '__main__':
    main()
