"""
Tests for Folder Domain - Entity, Service, and Repository.

@module tests.domains.test_folder_domain
@version 1.0.0 (v3.33 Workspace + Tag Phase 2.6)

Tests:
- FolderColor enum
- FolderType enum
- Folder entity
- FolderService business logic
"""

import pytest
from datetime import datetime
from unittest.mock import AsyncMock, MagicMock, patch


# ==========================================
# Test FolderColor enum
# ==========================================

class TestFolderColor:
    """Tests for FolderColor enum"""

    def test_all_colors_defined(self):
        """Test that all 8 colors are defined."""
        from domains.folder.entities import FolderColor

        assert len(FolderColor) == 8
        assert FolderColor.SLATE.value == "slate"
        assert FolderColor.RED.value == "red"
        assert FolderColor.ORANGE.value == "orange"
        assert FolderColor.AMBER.value == "amber"
        assert FolderColor.EMERALD.value == "emerald"
        assert FolderColor.CYAN.value == "cyan"
        assert FolderColor.BLUE.value == "blue"
        assert FolderColor.VIOLET.value == "violet"

    def test_from_str_valid(self):
        """Test from_str with valid color strings."""
        from domains.folder.entities import FolderColor

        assert FolderColor.from_str("slate") == FolderColor.SLATE
        assert FolderColor.from_str("RED") == FolderColor.RED
        assert FolderColor.from_str("Orange") == FolderColor.ORANGE

    def test_from_str_invalid_returns_default(self):
        """Test from_str with invalid color returns SLATE."""
        from domains.folder.entities import FolderColor

        assert FolderColor.from_str("invalid") == FolderColor.SLATE
        assert FolderColor.from_str("") == FolderColor.SLATE
        assert FolderColor.from_str("purple") == FolderColor.SLATE


# ==========================================
# Test FolderType enum
# ==========================================

class TestFolderType:
    """Tests for FolderType enum"""

    def test_types_defined(self):
        """Test that both folder types are defined."""
        from domains.folder.entities import FolderType

        assert len(FolderType) == 2
        assert FolderType.PROJECT.value == "project"
        assert FolderType.ASSET.value == "asset"

    def test_from_str_valid(self):
        """Test from_str with valid type strings."""
        from domains.folder.entities import FolderType

        assert FolderType.from_str("project") == FolderType.PROJECT
        assert FolderType.from_str("ASSET") == FolderType.ASSET
        assert FolderType.from_str("Project") == FolderType.PROJECT

    def test_from_str_invalid_raises_error(self):
        """Test from_str with invalid type raises ValueError."""
        from domains.folder.entities import FolderType
        import pytest

        with pytest.raises(ValueError, match="Invalid folder type"):
            FolderType.from_str("invalid")

        with pytest.raises(ValueError, match="Invalid folder type"):
            FolderType.from_str("template")


# ==========================================
# Test Folder entity
# ==========================================

class TestFolderEntity:
    """Tests for Folder entity dataclass"""

    def test_create_new(self):
        """Test create_new factory method."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        folder = Folder.create_new(
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            name="My Folder",
            created_by="user_456",
            color=FolderColor.BLUE,
        )

        assert folder.workspace_id == "ws_123"
        assert folder.folder_type == FolderType.PROJECT
        assert folder.name == "My Folder"
        assert folder.created_by == "user_456"
        assert folder.color == FolderColor.BLUE
        assert folder.sort_order == 0
        # Note: ID is generated by database, not by create_new
        assert folder.id is None
        # created_at/updated_at are set by database
        assert folder.created_at is None
        assert folder.updated_at is None

    def test_create_new_default_color(self):
        """Test create_new uses SLATE as default color."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        folder = Folder.create_new(
            workspace_id="ws_123",
            folder_type=FolderType.ASSET,
            name="Assets",
            created_by="user_456",
        )

        assert folder.color == FolderColor.SLATE

    def test_to_dict(self):
        """Test to_dict method."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        folder = Folder(
            id="folder_abc",
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            name="Test Folder",
            color=FolderColor.EMERALD,
            sort_order=5,
            created_by="user_456",
            created_at=datetime(2026, 1, 28, 10, 0, 0),
            updated_at=datetime(2026, 1, 28, 12, 0, 0),
        )

        result = folder.to_dict()

        assert result["id"] == "folder_abc"
        assert result["workspace_id"] == "ws_123"
        assert result["folder_type"] == "project"
        assert result["name"] == "Test Folder"
        assert result["color"] == "emerald"
        assert result["sort_order"] == 5
        assert result["created_by"] == "user_456"
        assert "created_at" in result
        assert "updated_at" in result

    def test_from_dict(self):
        """Test from_dict method."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        data = {
            "id": "folder_xyz",
            "workspace_id": "ws_789",
            "folder_type": "asset",
            "name": "My Assets",
            "color": "violet",
            "sort_order": 3,
            "created_by": "user_abc",
            "created_at": "2026-01-28T10:00:00",
            "updated_at": "2026-01-28T12:00:00",
        }

        folder = Folder.from_dict(data)

        assert folder.id == "folder_xyz"
        assert folder.workspace_id == "ws_789"
        assert folder.folder_type == FolderType.ASSET
        assert folder.name == "My Assets"
        assert folder.color == FolderColor.VIOLET
        assert folder.sort_order == 3
        assert folder.created_by == "user_abc"


# ==========================================
# Test FolderService
# ==========================================

class TestFolderService:
    """Tests for FolderService business logic"""

    @pytest.fixture
    def mock_repository(self):
        """Create a mock folder repository."""
        return AsyncMock()

    @pytest.fixture
    def folder_service(self, mock_repository):
        """Create a FolderService with mocked repository."""
        from domains.folder.service import FolderService
        return FolderService(mock_repository)

    @pytest.mark.asyncio
    async def test_create_folder(self, folder_service, mock_repository):
        """Test creating a folder."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        mock_repository.get_by_workspace_and_name.return_value = None
        mock_repository.count_items.return_value = 0

        created_folder = Folder(
            id="new_folder_id",
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            name="New Folder",
            color=FolderColor.BLUE,
            sort_order=0,
            created_by="user_456",
        )
        mock_repository.create.return_value = created_folder

        result = await folder_service.create_folder(
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            name="New Folder",
            created_by="user_456",
            color=FolderColor.BLUE,
        )

        assert result.name == "New Folder"
        assert result.workspace_id == "ws_123"
        mock_repository.create.assert_called_once()

    @pytest.mark.asyncio
    async def test_create_folder_duplicate_name_db_constraint(self, folder_service, mock_repository):
        """Test creating a folder with duplicate name - handled by DB constraint."""
        from domains.folder.entities import FolderType, FolderColor

        # Simulate database constraint error
        mock_repository.create.side_effect = Exception("duplicate key value violates unique constraint")

        with pytest.raises(Exception, match="duplicate"):
            await folder_service.create_folder(
                workspace_id="ws_123",
                folder_type=FolderType.PROJECT,
                name="Existing Folder",
                created_by="user_456",
            )

    @pytest.mark.asyncio
    async def test_list_folders(self, folder_service, mock_repository):
        """Test listing folders."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        mock_folders = [
            Folder(id="f1", workspace_id="ws_123", folder_type=FolderType.PROJECT,
                   name="Folder A", color=FolderColor.SLATE, sort_order=0, created_by="user"),
            Folder(id="f2", workspace_id="ws_123", folder_type=FolderType.PROJECT,
                   name="Folder B", color=FolderColor.BLUE, sort_order=1, created_by="user"),
        ]
        mock_repository.get_by_workspace.return_value = mock_folders

        result = await folder_service.list_folders("ws_123", FolderType.PROJECT)

        assert len(result) == 2
        assert result[0].name == "Folder A"
        assert result[1].name == "Folder B"
        mock_repository.get_by_workspace.assert_called_once_with("ws_123", FolderType.PROJECT)

    @pytest.mark.asyncio
    async def test_validate_folder_access_valid(self, folder_service, mock_repository):
        """Test validate_folder_access returns True for valid access."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        folder = Folder(
            id="folder_id",
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            name="Test",
            color=FolderColor.SLATE,
            sort_order=0,
            created_by="user",
        )
        mock_repository.get_by_id.return_value = folder

        result = await folder_service.validate_folder_access("folder_id", "ws_123")

        assert result is True

    @pytest.mark.asyncio
    async def test_validate_folder_access_wrong_workspace(self, folder_service, mock_repository):
        """Test validate_folder_access returns False for wrong workspace."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        folder = Folder(
            id="folder_id",
            workspace_id="ws_other",
            folder_type=FolderType.PROJECT,
            name="Test",
            color=FolderColor.SLATE,
            sort_order=0,
            created_by="user",
        )
        mock_repository.get_by_id.return_value = folder

        result = await folder_service.validate_folder_access("folder_id", "ws_123")

        assert result is False

    @pytest.mark.asyncio
    async def test_validate_folder_access_not_found(self, folder_service, mock_repository):
        """Test validate_folder_access returns False when folder not found."""
        mock_repository.get_by_id.return_value = None

        result = await folder_service.validate_folder_access("nonexistent", "ws_123")

        assert result is False

    @pytest.mark.asyncio
    async def test_delete_folder(self, folder_service, mock_repository):
        """Test deleting a folder."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        folder = Folder(
            id="folder_id",
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            name="Test",
            color=FolderColor.SLATE,
            sort_order=0,
            created_by="user",
        )
        mock_repository.get_by_id.return_value = folder
        mock_repository.delete.return_value = True

        result = await folder_service.delete_folder("folder_id")

        assert result is True
        mock_repository.delete.assert_called_once_with("folder_id", workspace_id="ws_123")

    @pytest.mark.asyncio
    async def test_update_folder(self, folder_service, mock_repository):
        """Test updating a folder."""
        from domains.folder.entities import Folder, FolderType, FolderColor

        # Setup: existing folder for name conflict check
        existing_folder = Folder(
            id="folder_id",
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            name="Old Name",
            color=FolderColor.SLATE,
            sort_order=0,
            created_by="user",
        )
        mock_repository.get_by_id.return_value = existing_folder
        mock_repository.get_by_workspace_and_name.return_value = None  # No conflict

        updated_folder = Folder(
            id="folder_id",
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            name="Updated Name",
            color=FolderColor.VIOLET,
            sort_order=0,
            created_by="user",
        )
        mock_repository.update_partial.return_value = updated_folder

        result = await folder_service.update_folder(
            folder_id="folder_id",
            name="Updated Name",
            color=FolderColor.VIOLET,
        )

        assert result.name == "Updated Name"
        assert result.color == FolderColor.VIOLET

    @pytest.mark.asyncio
    async def test_reorder_folders(self, folder_service, mock_repository):
        """Test reordering folders."""
        from domains.folder.entities import FolderType

        mock_repository.reorder.return_value = True

        result = await folder_service.reorder_folders(
            workspace_id="ws_123",
            folder_type=FolderType.PROJECT,
            folder_ids=["f1", "f2", "f3"],
        )

        assert result is True
        mock_repository.reorder.assert_called_once_with("ws_123", FolderType.PROJECT, ["f1", "f2", "f3"])
